name: CI/CD Android Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      EAS_NO_VCS: 1 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install EAS CLI
        run: npm install -g eas-cli@latest

      - name: Install dependencies
        run: npm install

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Decode Keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android.jks

      # Create the credentials.json that EAS looks for in 'local' mode
      - name: Create Credentials JSON
        run: |
          echo '{
            "android": {
              "keystore": {
                "keystorePath": "android.jks",
                "keystorePassword": "${{ secrets.KEYSTORE_PASSWORD }}",
                "keyAlias": "${{ secrets.KEY_ALIAS }}",
                "keyPassword": "${{ secrets.KEY_PASSWORD }}"
              }
            }
          }' > credentials.json

      - name: Generate Native Folder
        run: npx expo prebuild --platform android

      - name: Build APK Locally
        # The --local flag uses the credentials.json we just created
        run: eas build --platform android --profile production --non-interactive --local --output=./app-release.apk

      - name: Verify APK Signature Presence
        # If this fails, the APK is unsigned and Firebase will reject it
        run: |
          sudo apt-get update && sudo apt-get install -y aapt
          aapt dump badging ./app-release.apk | grep package

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Distribute to Firebase
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=firebase-key.json
          firebase appdistribution:distribute ./app-release.apk \
          --app "1:773349551035:android:152ae5a7db9ef1aff3729e" \
          --groups "testers"