name: CI/CD Android Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Fixed: Updated to 20

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Install dependencies
        run: npm install

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Decode Android keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android.jks

      # This creates the android folder so we can build it here
      - name: Generate Native Android Folder
        run: npx expo prebuild --platform android

      # IMPORTANT: Use --local and --output to keep the file here for Firebase
      - name: Build APK Locally
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform android --profile production --non-interactive --local --output=./app-release.apk

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Distribute to Firebase
        run: |
          firebase appdistribution:distribute ./app-release.apk \
          --app "1:773349551035:android:152ae5a7db9ef1aff3729e" \
          --groups "testers" \
          --token "${{ secrets.FIREBASE_TOKEN }}"